### ISSUE TITLE
July/August 2022 newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#9]
Creating draft newsletter for July/August 2022

**_Feel free to post ongoing events or updates here, to be added to the newsletter_**

## [Tasks before release](https://the-turing-way.netlify.app/community-handbook/newsletters/newsletters-process.html)

- [x] Collect events from past month (since mid-June 2022)
- [x] Review draft on HackMD (send me an email to review [asteele@turing.ac.uk](mailto:asteele@turing.ac.uk)
- [x] Post on Github
- [ ] Review PR
- [ ] Publish on Tiny Letter
- [ ] Promote more broadly on Twitter, Turing Slack

## Template:
💬 : Community News
🪐 : in _The Turing Way_ orbit
📆 : Upcoming events & opportunities
